#load libraries I am using
library(msa)
library(Biostrings)
library(seqinr)
library(phangorn)
library(tidyr)
library(dplyr)
# go to working directory with sequence of homo-sapiens
setwd("~/Documents/GitHub/Bioinformatics/") # can't set working 'directory' to a file, has to be a folder
# attach files and assign each a variable
# perform Multiple Sequence Alignment
seqmid <- readDNAStringSet("sequences-2.fasta")
seqmid
myAlignment <- msa(seqmid, "ClustalW")
myAlignment
# Gene is Hemoglobin Subunit Beta
# Translate sequence to protein 
# what sequence is this??
Midseq1 <- ("AATCTACTCCCAGGAGCAGGGAGGGCAGGAGCCAG 
            GCTGGGCATGAAAGTCAGGGCAGAGCCATCTATTGCTTACATTTGCTTCTGACACAACTGTGTTCACTAG
            CAACCTCAAACAGACACCATGGTGCACCTGACTCCTGTGGAGAAGTCTGCCGTTACTGCCCTGTGGGGCA
            AGGTGAACGTGGATGAAGTTGGTGGTGAGGCCCTGGGCAGGTTGGTATCAAGGTTACAAGACAGGTTTAA
            GGAGACCAATAGAAACTGGGCATGTGGAGACAGAGAAGACTCTTGGGTTTCTGATAGGCACTGACTCTCT
            CTGCCTATTGGTCTATTTTCCCACCCTTAGGCTGCTGGTGGTCTACCCTTGGACCCAGAGGTTCTTTGAG
            TCCTTTGGGGATCTGTCCACTCCTGATGCTGTTATGGGCAACCCTAAGGTGAAGGCTCATGGCAAGAAAG
            TGCTCGGTGCCTTTAGTGATGGCCTGGCTCACCTGGACAACCTCAAGGGCACCTTTGCCACACTGAGTGA
            GCTGCACTGTGACAAGCTGCACGTGGATCCTGAGAACTTCAGGGTGAGTCTATGGGACCCTTGATGTTTT
            CTTTCCCCTTCTTTTCTATGGTTAAGTTCATGTCATAGGAAGGGG")
# Midseq1 <- DNAString("
# AATCTACTCCCAGGAGCAGGGAGGGCAGGAGCCAGG
# GCTGGGCATGAAAGTCAGGGCAGAGCCATCTATTGCTTACATTTGCTTCTGACACAACTGTGTTCACTAG
# CAACCTCAAACAGACACCATGGTGCACCTGACTCCTGTGGAGAAGTCTGCCGTTACTGCCCTGTGGGGCA
# AGGTGAACGTGGATGAAGTTGGTGGTGAGGCCCTGGGCAGGTTGGTATCAAGGTTACAAGACAGGTTTAA
# GGAGACCAATAGAAACTGGGCATGTGGAGACAGAGAAGACTCTTGGGTTTCTGATAGGCACTGACTCTCT
# CTGCCTATTGGTCTATTTTCCCACCCTTAGGCTGCTGGTGGTCTACCCTTGGACCCAGAGGTTCTTTGAG
# TCCTTTGGGGATCTGTCCACTCCTGATGCTGTTATGGGCAACCCTAAGGTGAAGGCTCATGGCAAGAAAG
# TGCTCGGTGCCTTTAGTGATGGCCTGGCTCACCTGGACAACCTCAAGGGCACCTTTGCCACACTGAGTGA
# GCTGCACTGTGACAAGCTGCACGTGGATCCTGAGAACTTCAGGGTGAGTCTATGGGACCCTTGATGTTTT
# CTTTCCCCTTCTTTTCTATGGTTAAGTTCATGTCATAGGAAGGGG")
Midseq1
# library(Biostrings) # library is already loaded
# fasta file
# 'file.fasta' doesn't exist
Midseq1 <- Biostrings::readDNAStringSet("file.fasta", format = "fasta", use.names = TRUE)
seqmid <- Biostrings::readDNAStringSet("file.fasta", format = "fasta", use.names = TRUE)
#3d picture attached to document. 
# Use Uniprot to figure out the protein
# Protein: Hemoglobin Subunit Beta
# Diseases associated: Sickle Cell, Anemia, Malaria Resistance etc
# 3D picture added to doc. (not added to the Bioinformatics folder)